version: "3.8"
services:
  mysql:
    build: cloud/mysql
    container_name: mysqlCloudContainer
    ports:
      - 3306:3306

  promotheus:
    build: cloud/promotheus
    container_name: prometheusCloudContainer
    ports:
      - 9090:9090